openapi: 3.0.0
info:
  title: Music Bands Service
  version: 1.0.0
  description: Простое API для взаимодействия с синглами и участниками музыкальных групп
servers:
  - url: 'https://localhost:8080/api/v1/grammy'

paths:
  /band/{band-id}/singles/add:
    post:
      summary: Создание нового сингла
      tags: 
        - Bands updates
      operationId: addSingle
      parameters:
        - name: band-id
          description: Идентификатор группы
          in: path
          required: true
          schema:
            type: number
            minimum: 1
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/Single"
      responses:
        '201':
          description: Успешно создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Band'
        '400':
            description: Ошибка. Неправильные параметры
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: integer
                      format: int32
                      example: 400
                    message:
                      type: string
                      example: Неправильные параметры
        '503':
          description: Сервер не доступен
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 503
                  message:
                    type: string
                    example: Сервер не доступен
        '404':
          description: Ошибка по умолчанию
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
  
  /bands/{band-id}/singles/{single-id}:
    put:
      summary: Изменение сингла
      tags: 
        - Bands updates
      operationId: changeSingle
      parameters:
        - name: band-id
          description: Идентификатор группы
          in: path
          required: true
          schema:
            type: number
            minimum: 1
        - name: single-id
          description: Идентификатор сингла
          in: path
          required: true
          schema:
            type: number
            minimum: 1
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/Single"
      responses:
        '200':
          description: Успешно обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Single'
        '400':
            description: Ошибка. Неправильные параметры
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: integer
                      format: int32
                      example: 400
                    message:
                      type: string
                      example: ['ID паспорта не может быть больше 22 символов']
        '503':
          description: Сервер не доступен
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 503
                  message:
                    type: string
                    example: Сервер не доступен
        '404':
          description: Ошибка по умолчанию
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'


  /band/{band-id}/participants/add:
    post:
      summary: Добавление участника в группу
      tags: 
        - Bands updates
      operationId: addParticipant
      parameters:
        - name: band-id
          description: Идентификатор группы
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
      responses:
        '201':
          description: Успешно создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
            description: Ошибка. Неправильные параметры
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: integer
                      format: int32
                      example: 400
                    message:
                      type: string
                      example: ['ID паспорта не может быть больше 22 символов']
        '503':
          description: Сервер не доступен
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 503
                  message:
                    type: string
                    example: Сервер не доступен
        '404':
          description: Ошибка по умолчанию
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'

components:
  schemas:
    Band:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          uniqueItems: true
          readOnly: true
        name:
          type: string
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
          readOnly: true
          default: "2011-12-03T10:15:30+01:00"
        numberOfParticipants:
          type: number
          format: int64
          minimum: 1
        description:
          type: string
        genre:
          $ref: '#/components/schemas/MusicGenre'
        frontMan:
          $ref: '#/components/schemas/Frontman'
        singles:
          type: array
          items:
            $ref: '#/components/schemas/Single'
      required:
        - id
        - name
        - coordinates
        - creationDate
        - numberOfParticipants
        - description
        - genre
          
    Person:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          uniqueItems: true
          readOnly: true
        name:
          type: string
          minLength: 1
        birthday:
          type: string
          format: date
          nullable: true
        passportID:
          type: string
          uniqueItems: true
        location:
          $ref: '#/components/schemas/Location'
        groupID:
          type: integer
      required:
        - id
        - passportID
        - location
        - groupID

    Single:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          uniqueItems: true
          readOnly: true
        name:
          type: string
          minLength: 1
          maxLength: 10
      required:
        - id
        - name

    Coordinates:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          uniqueItems: true
          readOnly: true
        x:
          type: number
          format: int64
        y:
          type: number
          format: double
          minimum: -439
          nullable: false
      required:
        - id
        - x
        - y
        
    Location:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          uniqueItems: true
          readOnly: true
        x:
          type: number
          format: float
          nullable: false
        y:
          type: number
          format: float
        z:
          type: integer
        name:
          type: string
          minLength: 1
          nullable: true
      required:
        - id
        - x
        - y
        - z
        
    MusicGenre:
      type: string
      enum:
        - ROCK
        - SOUL
        - MATH_ROCK
        - POST_ROCK

    DefaultError:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 404
        message:
          type: string
          example: Ресурс не найден
        
    Frontman:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
          uniqueItems: true
          readOnly: true
        name:
          type: string
          minLength: 1
        birthday:
          type: string
          format: date
          nullable: true
        passportID:
          type: string
          uniqueItems: true
        location:
          $ref: '#/components/schemas/Location'
      required:
        - id
        - passportID
        - location